name: daw2

services:
  # Frontend (Angular)
  frontend:
    image: node:20-alpine
    container_name: xuxemon-frontend
    volumes:
      - ./frontend:/app
    ports:
      - "4200:4200"
    command: sh -c "cd /app && npm install && npm start -- --host 0.0.0.0"
    networks:
      - red
    depends_on:
      backend:
        condition: service_started

  # Backend (Laravel)
  backend:
    build: .
    container_name: xuxemon-backend
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:80"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: basedatos
      DB_PORT: 3306
      DB_DATABASE: xuxemons_basedatos
      DB_USERNAME: dev_user
      DB_PASSWORD: 1234
    networks:
      - red
    depends_on:
      basedatos:
        condition: service_healthy

  # Base de Datos (MySQL)
  basedatos:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: xuxemons_basedatos
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - red
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_password"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:

networks:
  red:
    driver: bridge

